baseURL      = 'https://www.afoep.at/'
languageCode = 'de'
title        = 'AFÖP'

[params]
  address = 'Akademischer Fachverein Österreichischer Pharmazeut_innen / Kaiserstraße 40/10, 1070 Wien / ZVR 405502824'

  [params.social]
    facebook  = 'https://facebook.com/afoep/'
    instagram = 'https://www.instagram.com/afoep/'
    linkedin  = 'https://www.linkedin.com/company/akademischer-fachverein-%C3%B6sterreichischer-pharmazeut_innen'
